const SET_RESULTS = 'SET_RESULTS';
const SET_UNIT_RESULT = 'SET_UNIT_RESULT';
const SET_QUERY = 'SET_QUERY';
const SET_SEARCH_ERROR_MESSAGE = 'SET_SEARCH_ERROR_MESSAGE';
const SENDING_SEARCH_REQUEST = 'SENDING_SEARCH_REQUEST';

export {
  SET_RESULTS, SET_UNIT_RESULT, SET_QUERY,
  SET_SEARCH_ERROR_MESSAGE, SENDING_SEARCH_REQUEST,
};
