// Enterprise Edit
export const SET_ENTERPRISE_EDIT_HEADERS = 'SET_ENTERPRISE_EDIT_HEADERS';
export const SET_ENTERPRISE_EDIT_ID = 'SET_ENTERPRISE_EDIT_ID';
export const SENDING_ENTERPRISE_EDIT_REQUEST = 'SENDING_ENTERPRISE_EDIT_REQUEST';
export const SET_ENTERPRISE_EDIT_BODY = 'SET_ENTERPRISE_EDIT_BODY';
export const SET_ENTERPRISE_EDIT_ERROR_MESSAGE = 'SET_ENTERPRISE_EDIT_ERROR_MESSAGE';
