const SET_USER_DETAILS = 'SET_USER_DETAILS';
const SET_CONFETTI = 'SET_CONFETTI';
const CHECK_AUTH = 'CHECK_AUTH';
const SET_AUTH = 'SET_AUTH';
const SENDING_REQUEST = 'SENDING_REQUEST';
const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
const USER_LOGOUT = 'USER_LOGOUT';

export {
  SET_USER_DETAILS, SET_CONFETTI, CHECK_AUTH, SET_AUTH,
  SENDING_REQUEST, SET_ERROR_MESSAGE, USER_LOGOUT,
};
